project:
  type: website
  output-dir: _site

website:
  title: "CC400 - Diseños Experimentales y Cuasiexperimentales"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: assignments/index.qmd
        text: Trabajos prácticos
    right:
      - icon: github
        href: https://github.com/spiousas/practicos_CC400
  page-footer:
    center: "Materiales de CC400"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
